// <auto-generated />
using System;
using ErrorMonitoring.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ErrorMonitoring.Infra.Data.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20200726134627_all_tables")]
    partial class all_tables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ErrorMonitoring.Dominio.Entidades.Environments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EnvName")
                        .IsRequired()
                        .HasColumnName("envName")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("ENVIRONMENTS");
                });

            modelBuilder.Entity("ErrorMonitoring.Dominio.Entidades.Events", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EColectedBy")
                        .HasColumnName("eColectedBy")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<DateTime>("EDate")
                        .HasColumnName("eDate")
                        .HasColumnType("date");

                    b.Property<string>("EDescription")
                        .HasColumnName("eDescription")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("EException")
                        .HasColumnName("eException")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("ELevel")
                        .IsRequired()
                        .HasColumnName("eLevel")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("EMessage")
                        .HasColumnName("eMessage")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("EOrigin")
                        .HasColumnName("eOrigin")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("EStatus")
                        .IsRequired()
                        .HasColumnName("eStatus")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("EVENTS");
                });

            modelBuilder.Entity("ErrorMonitoring.Dominio.Entidades.Logs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<int>("Project")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("Project");

                    b.ToTable("LOGS");
                });

            modelBuilder.Entity("ErrorMonitoring.Dominio.Entidades.Projects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("IsDesktop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool?>("IsMobile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool?>("IsWeb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasColumnName("pName")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("PROJECTS");
                });

            modelBuilder.Entity("ErrorMonitoring.Dominio.Entidades.ProjectsEnvironments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Environment")
                        .HasColumnType("int");

                    b.Property<int>("Project")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Environment");

                    b.HasIndex("Project");

                    b.ToTable("PROJECTS_ENVIRONMENTS");
                });

            modelBuilder.Entity("ErrorMonitoring.Dominio.Entidades.Logs", b =>
                {
                    b.HasOne("ErrorMonitoring.Dominio.Entidades.Events", "EventTypeNavigation")
                        .WithMany("Logs")
                        .HasForeignKey("EventType")
                        .HasConstraintName("FK__LOGS__EventType__3C69FB99")
                        .IsRequired();

                    b.HasOne("ErrorMonitoring.Dominio.Entidades.Projects", "ProjectNavigation")
                        .WithMany("Logs")
                        .HasForeignKey("Project")
                        .HasConstraintName("FK__LOGS__Project__3B75D760")
                        .IsRequired();
                });

            modelBuilder.Entity("ErrorMonitoring.Dominio.Entidades.ProjectsEnvironments", b =>
                {
                    b.HasOne("ErrorMonitoring.Dominio.Entidades.Environments", "EnvironmentNavigation")
                        .WithMany("ProjectsEnvironments")
                        .HasForeignKey("Environment")
                        .HasConstraintName("FK__PROJECTS___Envir__412EB0B6")
                        .IsRequired();

                    b.HasOne("ErrorMonitoring.Dominio.Entidades.Projects", "ProjectNavigation")
                        .WithMany("ProjectsEnvironments")
                        .HasForeignKey("Project")
                        .HasConstraintName("FK__PROJECTS___Proje__403A8C7D")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
