
USE ErrorMonitoring;
GO

SELECT * FROM LOGS
SELECT * FROM EVENTS

SELECT * FROM USERS

SELECT * FROM ENVIRONMENTS
SELECT * FROM TECNOLOGYS

SELECT * FROM PROJECTS

SELECT * FROM PROJECTS_ENVIRONMENTS
SELECT * FROM PROJECTS_TECNOLOGYS

SELECT * FROM PROJECTS_USERS
